name: Complete CI setup for Flutter app
on:
  pull_request:
    branches:
      - master

jobs:
  run-static-checks:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
