ftl-config:
  type: instrumentation
  app: build/app/outputs/apk/debug/app-debug.apk
  test: build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  device:
    - model: Pixel3
      version: 30
    - model: Pixel2
      version: 29
    - model: MediumPhone.arm
      version: 32
    - model: MediumPhone.arm
      version: 33
