name: Complete CI setup for Flutter app
on:
  pull_request:
    branches:
      - master

jobs:
  run-static-checks:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: "stable"
      - name: check code formatting
        run: flutter format . --set-exit-if-changed
      - name: check code linting
        run: flutter analyze .
  run-unit-tests:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: "stable"
      - name: Run test with coverage
        run: flutter test --coverage
      - name: Enforce code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 60
