android-pixel-4:
  type: instrumentation
  app: build/app/outputs/apk/debug/app-debug.apk
  test: build/app/outputs/apk/androidTest/debug/aapp-debug-androidTest.apk
  device:
    - model: Pixel3
      version: 32
      locale: "en"
      orientation: portrait
